export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const SIGN_UP_MENTOR = 'SIGN_UP_MENTOR';
export const SIGN_IN_MENTOR = 'SIGN_IN_MENTOR';
export const SIGN_OUT_MENTOR = 'SIGN_OUT_MENTOR';

export const FETCH_MENTORS = 'FETCH_UNAPPROVED_MENTORS';
export const APPROVE_MENTOR = 'APPROVE_MENTOR';
export const BAN_MENTOR = 'BAN_MENTOR';
export const REMOVE_MENTOR = 'REMOVE_MENTOR';
